//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineCourses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Deals = new HashSet<Deal>();
        }
    
        public int ID { get; set; }
        public int TeacherID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.TimeSpan> SheduleHour { get; set; }
        public string ScheduleDate { get; set; }
        public Nullable<System.DateTime> TimeExpire { get; set; }
        public string Link { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public string Category { get; set; }
        public string Photo { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deals { get; set; }
    }
}
