//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineCourses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int ID { get; set; }
        public int CourseID { get; set; }
        public int StudentID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string State { get; set; }
        public string Review { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Course Course { get; set; }
    }
}
